language: csharp
mono: none
dotnet: 2.1
env:
  global:
    secure: QRPwvkovTcwRpADIqbMOlgoxyr2pKYQf3dSE5et+VEmp2lNGIGslIFNhqB8qZmU5dj+xYXcBbNCuynjsCihKG9LfnoY8Cv+D45UgAb0OCmCHkFZwjBSXAmU66I9JkxOb4CbMc6PBuVidLcwRwNmVkyG6zXYR38jlnHiCFIg5+GhgFJCNjre+u3dAfV15mHD3twds6edHuJIcSXkucr6hZb4Cb1FeD5BCGGXQI/XPv7OjsX3K0flBr07LxbJoECHU6I7IlKjAQrr9tQ3JNtxRlURgZ+ITTZshRmUSGkxlKaC9goz32X90X4fVQ7+2gOmWj9btjd/eh159cxMauKvrz8q5xgFCgkVd2i/wIqWCyIJOiZbrOKNiX4rm2CcEmWk+OuHcsZ1eWTgppYRAQkxqpGt9nS/MSiAv8chAbK1pfYuQgoCdtYWWgOweUEsThNqfPQyh9SPq48Ck907oIsj6AdIEE0KzO/pbU8VQgw7A2NuD9m1DlDu9PkxQVsbOhMUEXvqv39MsxLTA/88+pw6el/bYXRFvWG+7/k7LfNv0DWG4Nrs7OGgBqr6wP9m40jfoDVnHZOeqCcu6E/zL5fDYj3GIPhpeTPXIY/2FHOkYO97N3ThFeMmrgyYlnL7NbMBnSu4IuH3HDkyCQQ/aRV04yWOU/ZWv5kqkO3QCLeZiSW4=
script:
- dotnet build -c Release
- dotnet test
before_deploy:
- dotnet pack -c Release -p:Version=$TRAVIS_TAG
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push /home/travis/build/rsocket/rsocket-net/RSocket.Core/bin/Release/RSocket.Core.*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
  on:
    tags: true
